-- Vocabulary expansion: rayon fabric + Nude/Blush colours (010-wardrobe-critic
-- follow-up, 2026-08-12, phase 2 of the demo-woman import — see plan.md
-- "Demo woman account" and backlog.md §AF). `clothing_items.material` FKs to
-- `fabric_types(name)` and `clothing_items.color` FKs to `colors(name)`; the
-- live catalogue (built from a menswear wardrobe) never needed `rayon` or the
-- pale-neutral colours `Nude`/`Blush`, which blocked 4 of 11 planned
-- womenswear items (blouse_white, dress_floral — both rayon; heels_nude,
-- camisole_blush — Nude/Blush). anh Khôi's call: extend the vocabulary at
-- every layer rather than remap to a nearby existing value.
--
-- Idempotent — safe to re-run.

-- rayon: reinstated cellulose fibre (viscose), light/breathable — same
-- weight/breathability/season bucket as the existing linen/silk rows.
insert into public.fabric_types (name, weight, breathability, season, style_boosts)
values ('rayon', 'light', 'high', 'summer', '{}')
on conflict (name) do nothing;

-- Nude / Blush: attrs generated by colorAttrsFromHex() in
-- generate-item-image/index.ts (the same function `ensureColors` calls for
-- any AI-discovered colour) run against the pixel-measured hexes
-- (#ba9276, #f5e1e0) — NOT hand-picked, to keep this row indistinguishable
-- from one the live ingest pipeline would have produced itself.
insert into public.colors
  (name, hex, tag, primary_color, lightness, saturation, hue, sat_pct, lum_pct, undertone, active)
values
  ('Nude',  '#ba9276', 'WARM', 'orange', 'medium', 'balanced', 25, 33, 60, 'warm', true),
  ('Blush', '#f5e1e0', 'WARM', 'red',    'light',  'balanced', 3,  51, 92, 'warm', true)
on conflict (name) do nothing;
